# Copyright (C) 2019 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the BSD License (3 clause, also known as the new BSD license)

version: '3'

services:

  django:
    depends_on:
      - base
      - postgres
      - rabbit
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "127.0.0.1:58000:8000"
    container_name: django_celery_beat
    entrypoint: ["/entrypoint.sh"]
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    tty: true
    #volumes:
    #  - './django_celery_beat/:/app/django_celery_beat/'
      #- '/home/marco/repos/JOBS/celery/tasks/tasks:/tasks/'

  rabbit:
    image: rabbitmq
    container_name: django_celery_beat-rabbitmq
    ports:
        - "5672:5672"
